### ISSUE TITLE
decode-secret - '<' character incorrectly decoded as \u003c 

### ISSUE THREAD

**Issue by jhevans** [ministryofjustice/cloud-platform-cli#103] opened 2021-07-21 12:50 UTC
Spotted in version 1.9.7 on Mac OSX Catalina 10.15.7

I stumbled across this issue recently with an automatically generated password. I've redacted the first part of the password and anything sensitive but fortunately the `<` character appears right at the end.

You can see from the terminal output below that the base64 returns a `<` as expected whereas we get some kind of Unicode character reference string back from `cloud-platform decode-secret`:

```
echo '...NS44NEU8' | base64 -D
...5.84E<
cloud-platform decode-secret -n court-probation-dev -s court-hearing-event-receiver
{
    "apiVersion": "v1",
    "data": {
       ...
        "A_SECRET": "...5.84E\u003c"
    },
    "kind": "Secret",
    "metadata": {
        "annotations": {

**Comment by jasonBirchall** [comment] 2022-08-19 14:48
This is still happening and easy to reproduce

**Comment by jasonBirchall** [comment] 2022-08-19 15:12
Looks like this is the json Marshalling:

> String values encode as JSON strings coerced to valid UTF-8, replacing invalid bytes with the Unicode replacement rune. The angle brackets "<" and ">" are escaped to "\u003c" and "\u003e" to keep some browsers from misinterpreting JSON output as HTML. Ampersand "&" is also escaped to "\u0026" for the same reason.

https://pkg.go.dev/encoding/json#Marshal

**Comment by jasonBirchall** [comment] 2022-08-22 14:15
Release 1.17.0 mitigates this issue using the --raw flag.

To print a unicode secret you can now:

```bash
cloud-platform decode-secret -n court-probation-dev -s court-hearing-event-receiver --raw
```

**Comment by jasonBirchall** [comment] 2022-08-22 14:54
Closing this issue @jhevans, feel free to re-open or dm me on slack if this mitigation isn't sufficiant.

**Closed by jasonBirchall** 2022-08-22 14:54 UTC
